### ISSUE TITLE
ServerTest doesn't work with 2D textures

### ISSUE THREAD

**Issue by codeanticode** [Syphon/Java#2]
@vade @bangnoise: The ServerTest example doesn't output valid textures when the texture target is [GL_TEXTURE_2D](https://github.com/Syphon/Java/blob/master/JSyphon/src/jsyphon/test/ServerTest.java#L60), SimpleClient shows a white screen. It works as expected when using GL_TEXTURE_RECTANGLE. Are 2D textures still supported by Syphon?

**Comment by vade** [comment]
They certainly should, we've received no reports indicating otherwise. Is the GL texture env setup so they  have appropriate wrapping and min/mag filters? Sometimes that messes up drawing? 

*The above is a shot in the dark* :)

**Comment by codeanticode** [comment]
Not sure what changed from earlier versions, but I will look into the texture setup... thanks for the suggestion.

**Comment by bangnoise** [comment]
If you've updated to the current framework, earlier versions used to set the texture state. We decided that's the job of the owner of the texture, not us.

**Comment by codeanticode** [comment]
That sounds promising. It is strange that the server example just works by switching to rectangle texture, but anyways, I will do some tests based on what you guys told me so far. Thanks!

**Comment by codeanticode** [comment]
yes, setting the tex params was the solution. https://github.com/Syphon/Java/commit/d8cbddf73abd982b832abf3b7f1fed26b2a6550b
