### ISSUE TITLE
Cannot archive JSypon Xcode project

### ISSUE THREAD

**Issue by codeanticode** [Syphon/Java#4]
The archive build fails with the following error:

```
Unable to run command 'PBXCp Syphon.framework' - this target might include its own product.
```

![image](https://user-images.githubusercontent.com/62246/30249965-d9b67b06-9614-11e7-8a5e-04149af3383c.png)

OS X 10.11.6, Xcode 8.2.1

**Comment by codeanticode** [comment]
@bangnoise do you know how can I properly archive the jsyphon project in XCode? See the error I get in the previous image.

**Comment by bangnoise** [comment]
Will take a look
