### ISSUE TITLE
Implement in Website

### ISSUE THREAD

**Issue by luisArandas** [Syphon/Java#5]
Any possibility of porting this into javascript?
Need an accurate syphon server of my js page.
Best, Luis

**Comment by bangnoise** [comment]
Don't think there's any way for JavaScript to invoke native code, so I'm guessing no.

You would need a browser which can render to Syphon:
@vade started work on support for Chromium https://github.com/vade/chromium
I also see https://github.com/glowbox/ChromeSyphon

You could also use any of the various apps which both render web pages and support Syphon - Resolume, VDMX, TouchDesigner, etc.
